name: e2e

networks:
  e2e-net: {}

services:
  admin-api:
    image: admin-api:local
    build:
      context: ../admin-api
      dockerfile: ../admin-api/Dockerfile
    ports:
      - 8081
    networks:
      e2e-net:
        aliases:
          - admin-api.localtest.me

  cypress:
    image: cypress:local
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - BROWSER=electron
      - CYPRESS_baseUrl=http://admin-api.localtest.me:8081
    depends_on:
      - admin-api
    volumes:
      - ./cypress:/app/cypress
      - ./reporter:/app/reporter
    networks:
      - e2e-net
