name: Cypress Tests

on:
  workflow_dispatch: {}
  push:
    branches: ["dev", "feature/*"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: testsuite
    steps:
      - uses: actions/checkout@v2
      - name: Pull any base images from registries
        run: |
          docker compose pull -q --ignore-buildable

      - name: Build custom images
        run: |
          docker compose build

      - name: Start E2E tests
        run: |
          docker compose up --abort-on-container-exit

      - name: Upload E2E test results HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-results-html
          path: ${{ github.workspace }}/testsuite/reporter/results
