name: Cypress Tests

on:
  workflow_dispatch: {}
  push:
    branches: ["dev", "feature/*"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: |
          cd testsuite
          docker compose build

      - name: Start E2E Tests
        run: |
          cd testsuite
          docker compose up -d

      - name: Wait for E2E Tests to finish & Clean Up
        run: |
          cd testsuite
          while true; do
            if [ "$(docker ps -aq -f status=exited -f name=e2e-cypress-1)" ]; then
              # cleanup
              docker compose down
              break
            else
              echo  "Waiting for Cypress to Complete E2E Tests....."
              docker compose logs cypress -n 5
              sleep 10s
            fi
          done

      - name: Upload E2E Test Results HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: test-results-html
          path: ${{ github.workspace }}/e2e/results/report
